version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '.\Test.Automation.ProjectExample.MSTest\bin\Release\*.log'
- path: '.\Test.Automation.ProjectExample.MSTest\bin\Release\*.png'
- path: '.\Test.Automation.ProjectExample.MSTest\bin\Release\*.html'