version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '.\Test.Automation.ProjectExample.MsTest\bin\Debug\*.log'
- path: '.\Test.Automation.ProjectExample.MsTest\bin\Debug\*.png'
- path: '.\Test.Automation.ProjectExample.MsTest\bin\Debug\*.html'