version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
- ps: >-
    7z a testresults.zip .\Test.Automation.ProjectExample.MsTest\bin\Debug\**\*.png

    7z a testresults.zip .\Test.Automation.ProjectExample.MsTest\bin\Debug\**\*.html

    7z a testresults.zip .\Test.Automation.ProjectExample.MsTest\bin\Debug\**\*.log


    appveyor PushArtifact testresults.zip
